name: client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter
  stacked: ^3.1.0+2
  web_socket_channel: ^2.3.0
  http: ^0.13.5
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  intl:
  fluttermoji: ^1.0.1
  flutter_svg:
  multiavatar: ^0.1.5
  firebase_core: ^2.6.1
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.4


dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  socket_io_client: ^1.0.2
  drift_dev: ^2.5.1

flutter:
  uses-material-design: true
 

